INSERT INTO ACCOUNTING_CODES VALUES( 1011,"Capital souscrit – non appelé",	"Compte de passif",	"Compte de bilan"),
    (1012,"Capital souscrit – appelé, non versé","Compte de passif",	"Compte de bilan"),
            (1013,"Capital souscrit – appelé, versé","Compte de passif","Compte de bilan"),
            (1018,"Capital souscrit soumis à des réglementations particulières","Compte de passif","Compte de bilan"),
            (102,"Fonds fiduciaires",	"Compte de passif",	"Compte de bilan"),
            (1042,"Primes de fusion","Compte de passif",	"Compte de bilan"),
            (1041,"	Primes d''émission","Compte de passif","Compte de bilan"),
            (1043,"Primes d''apport","Compte de passif","Compte de bilan"),
            (1044,"Primes de conversion d''obligations en actions","Compte de passif","Compte de bilan"),
            (1045,"Bons de souscription d''actions","Compte de passif","Compte de bilan"),
            (1051,"Réserve spéciale de réévaluation","Compte de passif","Compte de bilan"),
            (1052,"Ecart de réévaluation libre","Compte de passif","Compte de bilan"),
            (1053,"Réserve de réévaluation","Compte de passif","Compte de bilan"),
            (1055,"Ecarts de réévaluation (autres opérations légales)","Compte de passif","Compte de bilan"),
            (1057,"Autres écarts de réévaluation en France","Compte de passif","Compte de bilan"),
            (1058,"Autres écarts de réévaluation à l''Etranger","Compte de passif","Compte de bilan"),
            (1061,"Réserve légale",	"Compte de passif",	"Compte de bilan"),
            (1062,"Réserves indisponibles","Compte de passif",	"Compte de bilan"),
            (1063,"Réserves statutaires ou contractuelles",	"Compte de passif", 	"Compte de bilan"),
            (1064,"Réserves réglementées",	"Compte de passif", "Compte de bilan"),
            (1068,"Autres réserves",	"Compte de passif",	"Compte de bilan"),
            (107,"Ecart d''équivalence",	"Compte de passif",	"Compte de bilan"),
            (108,"Compte de l''exploitant","Compte de passif", "Compte de bilan"),
            (109,"Actionnaires : Capital souscrit - non appelé","Compte d''actif","Compte de bilan"),
            (110,"Report à nouveau (solde créditeur)",	"Compte de passif",	"Compte de bilan"),
            (119,"Report à nouveau (solde débiteur)",	"Compte de passif", 	"Compte de bilan"),
            (120,"Résultat de l''exercice (bénéfice)",	"Compte de passif",	"Compte de bilan"),
            (129,"Résultat de l''exercice (perte)",	"Compte de passif",	"Compte de bilan"),
            (131,"Subventions d''équipement",	"Compte de passif"	,"Compte de bilan"),
            (1311,"Subventions d''équipement - Etat",	"Compte de passif"	,"Compte de bilan"),
            (1313,"Subventions d''équipement - Départements",	"Compte de passif",	"Compte de bilan"),
            (1312,"Subventions d''équipement - Régions",	"Compte de passif",	"Compte de bilan"),
            (1314,"Subventions d''équipement - Communes",	"Compte de passif",	"Compte de bilan"),
            (1315,"Subventions d''équipement - Collectivités publiques",	"Compte de passif",	"Compte de bilan"),
            (1316,"Subventions d''équipement - Entreprises publiques",	"Compte de passif",	"Compte de bilan"),
            (1317,"Subventions d''équipement - Entreprises et organismes privés",	"Compte de passif",	"Compte de bilan"),
            (1318,"Subventions d''équipement - Autres",	"Compte de passif",	"Compte de bilan"),
            (138,"Autres subventions d’investissement",	"Compte de passif",	"Compte de bilan"),
            (139,"Subventions d''investissement inscrites au compte de résultat","Compte de passif",	"Compte de bilan"),
            (1391,"Subventions d''équipement",	"Compte de passif",	"Compte de bilan"),
            (13911,"Subventions d''équipement - Etat",	"Compte de passif",	"Compte de bilan"),
            (13912,"Subventions d''équipement - Régions",	"Compte de passif",	"Compte de bilan"),
            (13913,"Subventions d''équipement - Départements",	"Compte de passif",	"Compte de bilan"),
            (13914,"Subventions d''équipement - Communes",	"Compte de passif",	"Compte de bilan"),
            (13915,"Subventions d''équipement - Collectivités publiques",	"Compte de passif",	"Compte de bilan"),
            (13916,"Subventions d''équipement - Entreprises publiques",	"Compte de passif","Compte de bilan"),
            (13917,"Subventions d''équipement - Entreprises et organismes privés",	"Compte de passif",	"Compte de bilan"),
            (13918,"Subventions d''équipement - Autres",	"Compte de passif",	"Compte de bilan"),
            (1398,"Autres subventions d’investissement",	"Compte de passif",	"Compte de bilan"),
            (142,"Provisions réglementées relatives aux immobilisations",	"Compte de passif",	"Compte de bilan"),
            (1423,"Provisions pour reconstitution des gisements miniers et pétroliers",	"Compte de passif",	"Compte de bilan"),
            (1424,"Provisions pour investissement (participation des salariés)",	"Compte de passif",	"Compte de bilan"),
            (143,"Provisions réglementées relatives aux stocks",	"Compte de passif",	"Compte de bilan"),
            (1431,"Provisions réglementées relatives aux stocks - Hausse de prix",	"Compte de passif",	"Compte de bilan"),
            (1432,"Provisions réglementées relatives aux stocks - Fluctuation des cours",	"Compte de passif",	"Compte de bilan"),
            (144,"Provisions réglementées relatives aux autres éléments de l''actif",	"Compte de passif",	"Compte de bilan"),
            (145,"Amortissements dérogatoires",	"Compte de passif",	"Compte de bilan"),
            (146,"Provision spéciale de réévaluation",	"Compte de passif",	"Compte de bilan"),
            (147,"Plus-values réinvesties",	"Compte de passif"	,"Compte de bilan"),
            (148,"Autres provisions réglementées",	"Compte de passif",	"Compte de bilan"),
            (151,"Provisions pour risques",	"Compte de passif",	"Compte de bilan"),
            (1511,"Provisions pour litiges",	"Compte de passif",	"Compte de bilan"),
            (1512,"Provisions pour garanties données aux clients",	"Compte de passif",	"Compte de bilan"),
            (1513,"Provisions pour pertes sur marchés à terme",	"Compte de passif",	"Compte de bilan"),
            (1514,"Provisions pour amendes et pénalités",	"Compte de passif",	"Compte de bilan"),
            (1515,"Provisions pour pertes de change",	"Compte de passif",	"Compte de bilan"),
            (1516,"Provisions pour pertes sur contrats",	"Compte de passif",	"Compte de bilan"),
            (1518,"Autres provisions pour risques",	"Compte de passif",	"Compte de bilan"),
            (153,"Provisions pour pensions et obligations similaires",	"Compte de passif",	"Compte de bilan"),
            (154,"Provisions pour restructurations",	"Compte de passif",	"Compte de bilan"),
            (155,"Provisions pour impôts",	"Compte de passif",	"Compte de bilan"),
            (156,"Provisions pour renouvellement des immobilisations (entreprises concessionnaires)","Compte de passif",	"Compte de bilan"),
            (157,"Provisions pour charges à répartir sur plusieurs exercices",	"Compte de passif",	"Compte de bilan"),
            (158,"Autres provisions pour charges",	"Compte de passif",	"Compte de bilan"),
            (1581,"Provisions pour remises en état",	"Compte de passif",	"Compte de bilan"),
            (161,"Emprunts obligataires convertibles", "Compte de passif",	"Compte de bilan"),
(162,"Obligations représentatives de passifs nets remis en fiducie",	"Compte de passif",	"Compte de bilan"),
            (163,"Autres emprunts obligataires",	"Compte de passif",	"Compte de bilan"),
            (164,"Emprunts auprès des établissements de crédit",	"Compte de passif",	"Compte de bilan"),
            (165,"Dépôts et cautionnements reçus",	"Compte de passif",	"Compte de bilan"),
            (166,"Participation des salariés aux résultats",	"Compte de passif",	"Compte de bilan"),
            (1661,"Participation des salariés aux résultats - Comptes bloqués",	"Compte de passif",	"Compte de bilan"),
            (1662,"Participation des salariés aux résultats - Fonds de participation",	"Compte de passif",	"Compte de bilan"),
            (167,"Emprunts et dettes assortis de conditions particulières",	"Compte de passif",	"Compte de bilan"),
            (168,"Autres emprunts et dettes assimilées",	"Compte de passif",	"Compte de bilan"),
            (1681,"Autres emprunts et dettes assimilées - Autres emprunts",	"Compte de passif",	"Compte de bilan"),
            (1685,"Autres emprunts et dettes assimilées - Rentes viagères capitalisées",	"Compte de passif",	"Compte de bilan"),
            (1687,"Autres emprunts et dettes assimilées - Autres dettes",	"Compte de passif",	"Compte de bilan"),
            (1688,"Autres emprunts et dettes assimilées - Intérêts courus",	"Compte de l''actif ou de passif",	"Compte de bilan"),
            (   169,"Primes de remboursement des obligations",	"Compte d''actif",	"Compte de bilan"),
            (    171,"Dettes rattachées à des participations (groupe)",	"Compte de passif",	"Compte de bilan"),
            (174,"Dettes rattachées à des participations (hors groupe)",	"Compte de passif",	"Compte de bilan"),
            (178,"Dettes rattachées à des sociétés en participation",	"Compte de passif",	"Compte de bilan"),
            (181,"Comptes de liaison des établissements",	"Compte de passif",	"Compte de bilan"),
            (186,"Biens et prestations de services échangés entre établissements (charges)",	"Compte de passif",	"Compte de bilan"),
            (187,"Biens et prestations de services échangés entre établissements (produits)",	"Compte de passif",	"Compte de bilan"),
            (188,"Comptes de liaison des sociétés en participation",	"Compte de passif",	"Compte de bilan"),
            (101,"Capital",	"Compte de passif",	"Compte de bilan"),
    -- Classe 2 : Les comptes d''immobilisations
            (    201,"Frais d''établissement",	"Compte d''actif",	"Compte de bilan"),
            (2011,"Frais de constitution",	"Compte d''actif",	"Compte de bilan"),
            (          2012,"Frais de premier établissement",	"Compte d''actif",	"Compte de bilan"),
            (         20121,"Frais de prospection",	"Compte d''actif",	"Compte de bilan"),
            (        20122,"Frais de publicité",	"Compte d''actif",	"Compte de bilan"),
            (       2013,"Frais d''augmentation de capital et d''opérations diverses (fusions, scissions, transformations)",	"Compte d''actif",	"Compte de bilan"),
            (         203,"Frais de recherche et de développement",	"Compte d''actif",	"Compte de bilan"),
            (      205,"Concessions et droits similaires, brevets, licences, marques, procédés, logiciels, droits et valeurs similaires",	"Compte d''actif",	"Compte de bilan"),
            (      206,"Droit au bail",	"Compte d''actif",	"Compte de bilan"),
            (      207,"Fonds commercial",	"Compte d''actif",	"Compte de bilan"),
            (     208,"Autres immobilisations incorporelles",	"Compte d''actif",	"Compte de bilan"),
            (     211,"Terrains",	"Compte d''actif",	"Compte de bilan"),
            (     2111,"Terrains nus",	"Compte d''actif",	"Compte de bilan"),
            (   2112,"Terrains aménagés",	"Compte d''actif",	"Compte de bilan"),
            (   2113,"Sous - sols et sursols",	"Compte d''actif",	"Compte de bilan"),
            (   2114,"Terrains de gisement",	"Compte d''actif",	"Compte de bilan"),
            (   2115,"Terrains bâtis",	"Compte d''actif",	"Compte de bilan"),
            (  2116,"Compte d''ordre sur immobilisations",	"Compte d''actif",	"Compte de bilan"),
            (212,"Agencements et aménagements de terrains",	"Compte d''actif",	"Compte de bilan"),
            ( 213,"Constructions",	"Compte d''actif",	"Compte de bilan"),
            ( 2131,"Constructions - Bâtiments",	"Compte d''actif",	"Compte de bilan"),
            ( 2135,"Constructions - Installations générales - agencements – aménagements des constructions",	"Compte d''actif",	"Compte de bilan"),
            ( 2138,"Constructions - Ouvrages d''infrastructure",	"Compte d''actif",	"Compte de bilan"),
            (214,"Constructions sur sol d''autrui",	"Compte d''actif",	"Compte de bilan"),
            (215,"Installations techniques, matériels et outillage industriels",	"Compte d''actif",	"Compte de bilan"),
            (2151,"Installations complexes spécialisées",	"Compte d''actif",	"Compte de bilan"),
            ( 2153,"Installations à caractère spécifique",	"Compte d''actif",	"Compte de bilan"),
            ( 2154,"Matériel industriel",	"Compte d''actif",	"Compte de bilan"),
            ( 2155,"Outillage industriel",	"Compte d''actif",	"Compte de bilan"),
            ( 2157,"Agencements et aménagements du matériel et outillage industriels",	"Compte d''actif",	"Compte de bilan"),
            ( 218,"Autres immobilisations corporelles",	"Compte d''actif",	"Compte de bilan"),
            ( 2181,"Installations générales, agencements, aménagements divers",	"Compte d''actif",	"Compte de bilan"),
            ( 2182,"Matériel de transport",	"Compte d''actif",	"Compte de bilan"),
            (2183,"Matériel de bureau et matériel informatique",	"Compte d''actif",	"Compte de bilan"),
            (2184,"Mobilier",	"Compte d''actif",	"Compte de bilan"),
            (2185,"Cheptel",	"Compte d''actif",	"Compte de bilan"),
            (2186,"Emballages récupérables",	"Compte d''actif",	"Compte de bilan"),
            (22,"Immobilisations mises en concession",	"Compte d''actif",	"Compte de bilan"),
            (231,"Immobilisations corporelles en cours",	"Compte d''actif",	"Compte de bilan"),
            (2312,"Immobilisations corporelles en cours - Terrains",	"Compte d''actif",	"Compte de bilan"),
            (2313,"Immobilisations corporelles en cours - Constructions",	"Compte d''actif",	"Compte de bilan"),
            (2315,"Immobilisations corporelles en cours - Installations techniques, matériel et outillage industriels",	"Compte d''actif",	"Compte de bilan"),
            (2318,"Autres immobilisations corporelles en cours",	"Compte d''actif",	"Compte de bilan"),
            (232,"Immobilisations incorporelles en cours",	"Compte d''actif",	"Compte de bilan"),
            (237,"Avances et acomptes versés sur immobilisations incorporelles",	"Compte d''actif",	"Compte de bilan"),
            (238,"Avances et acomptes versés sur commandes d''immobilisations corporelles",	"Compte d''actif",	"Compte de bilan"),
            (25,"Parts dans des entreprises liées et créances sur des entreprises liées",	"Compte d''actif",	"Compte de bilan"),
            (261,"Titres de participation",	"Compte d''actif",	"Compte de bilan"),
            (266,"Autres formes de participation",	"Compte d''actif",	"Compte de bilan"),
            (267,"Créances rattachées à des participations",	"Compte d''actif",	"Compte de bilan"),
            (268,"Créances rattachées à des sociétés en participation",	"Compte d''actif",	"Compte de bilan"),
            (267,"Versements restant à effectuer sur titres de participation non libérés",	"Compte d''actif",	"Compte de bilan"),
            (271,"Titres immobilisés autres que les titres immobilisés de l''activité de portefeuille (droit de propriété)",	"Compte d''actif",	"Compte de bilan"),
            (272,"Titres immobilisés (droit de créance)",	"Compte d''actif",	"Compte de bilan"),
            (273,"Titres immobilisés de l''activité de portefeuille",	"Compte d''actif",	"Compte de bilan"),
            (274,"Prêts",	"Compte d''actif"	,"Compte de bilan"),
            (275,"Dépôts et cautionnements versés",	"Compte d''actif",	"Compte de bilan"),
            (276,"Autres créances immobilisées",	"Compte d''actif",	"Compte de bilan"),
            (2771,"Actions propres ou parts propres",	"Compte d''actif",	"Compte de bilan"),
            (2772,"Actions propres ou parts propres en voie d''annulation",	"Compte d''actif",	"Compte de bilan"),
            (279,"Versements restant à effectuer sur titres immobilisés non libérés",	"Compte d''actif",	"Compte de bilan"),
            (280,"Amortissements des immobilisations incorporelles",	"Compte d''actif",	"Compte de bilan"),
            (281,"Amortissements des immobilisations corporelles",	"Compte d''actif",	"Compte de bilan"),
            (282,"Amortissements des immobilisations mises en concession",	"Compte d''actif",	"Compte de bilan"),
            (290,"Dépréciations des immobilisations incorporelles",	"Compte d''actif",	"Compte de bilan"),
            (291,"Dépréciations des immobilisations corporelles",	"Compte d''actif",	"Compte de bilan"),
            (292,"Dépréciations des immobilisations mises en concession",	"Compte d''actif",	"Compte de bilan"),
            (293,"Dépréciations des immobilisations en cours",	"Compte d''actif",	"Compte de bilan"),
            (296,"Dépréciations des participations et créances rattachées à des participations",	"Compte d''actif",	"Compte de bilan"),
            (297,"Dépréciations des autres immobilisations financières",	"Compte d''actif",	"Compte de bilan"),
            (200,"Immobilisations incorporelles",	"Compte d''actif",	"Compte de bilan"),
            (210,"Immobilisations corporelles",	"Compte d''actif",	"Compte de bilan"),
            (2751,"Dépôts versés",	"Compte d''actif",	"Compte de bilan"),
     -- Classe 3 : Les comptes de stocks et en-cours
            (311,"Matières (ou groupe) A",	"Compte d''actif",	"Compte de bilan"),
            (312,"Matières (ou groupe) B",	"Compte d''actif",	"Compte de bilan"),
            (317,"Fournitures A, B, C",	"Compte d''actif",	"Compte de bilan"),
            (321,"Matières consommables",	"Compte d''actif",	"Compte de bilan"),
            (322,"Fournitures consommables",	"Compte d''actif",	"Compte de bilan"),
            (3221,"Fournitures consommables - Combustibles",	"Compte d''actif",	"Compte de bilan"),
            (3222,"Fournitures consommables - Produits d''entretien",	"Compte d''actif",	"Compte de bilan"),
            (3223,"Fournitures consommables - Fournitures d''atelier et d''usine",	"Compte d''actif",	"Compte de bilan"),
            (3224,"Fournitures de magasin",	"Compte d''actif",	"Compte de bilan"),
            (3225,"Fournitures de bureau",	"Compte d''actif",	"Compte de bilan"),
            (326,	"326 – Emballages",	"Compte d''actif",	"Compte de bilan"),
            (331,"Produits en cours",	"Compte d''actif",	"Compte de bilan"),
            (335,"Travaux en cours",	"Compte d''actif",	"Compte de bilan"),
            (341,"Etudes en cours",	"Compte d''actif",	"Compte de bilan"),
            (345,"Prestations de services en cours",	"Compte d''actif",	"Compte de bilan"),
            (351,"Stocks de produits intermédiaires",	"Compte d''actif",	"Compte de bilan"),
            (355,"Stocks de produits finis",	"Compte d''actif",	"Compte de bilan"),
            (358,"Stocks de produits résiduels (ou matières de récupération)",	"Compte d''actif",	"Compte de bilan"),
            (371,"Stocks de marchandises (ou groupe) A",	"Compte d''actif",	"Compte de bilan"),
            (372,"Stocks de marchandises (ou groupe) B",	"Compte d''actif",	"Compte de bilan"),
            (380,"Stock en voie d''acheminement",	"Compte d''actif",	"Compte de bilan"),
            (391,"Dépréciations des matières premières (et fournitures)",	"Compte d''actif",	"Compte de bilan"),
            (392,"Dépréciations des autres approvisionnements",	"Compte d''actif",	"Compte de bilan"),
            (393,"Dépréciations des en-cours de production de biens",	"Compte d''actif",	"Compte de bilan"),
            (394,"Dépréciations des en-cours de production de services",	"Compte d''actif",	"Compte de bilan"),
            (395,"Dépréciations des stocks de produits",	"Compte d''actif	Compte de bilan"),
            (397,"Dépréciations des stocks de marchandises",	"Compte d''actif	Compte de bilan"),


            -- Classe 4 : Les comptes de tiers
            (400,"Fournisseurs et comptes rattachés",	"Compte de l''actif ou de passif",	"Compte de bilan"),
            (401,"Fournisseurs",	"Compte de l''actif ou de passif",	"Compte de bilan"),
            (403,"Fournisseurs - Effets à payer",	"Compte de passif",	"Compte de bilan"),
            (404,"	Fournisseurs d''immobilisations",	"Compte de passif",	"Compte de bilan"),
            (405,"Fournisseurs d''immobilisations - Effets à payer",	"Compte de passif",	"Compte de bilan"),
            (408,"Fournisseurs - Factures non parvenues",	"Compte de passif",	"Compte de bilan"),
            (4091,"Fournisseurs - Avances et acomptes versés sur commandes",	"Compte d''actif",	"Compte de bilan"),
            (4096,"Fournisseurs - Créances pour emballages et matériel à rendre",	"Compte d''actif",	"Compte de bilan"),
            (4097,"Fournisseurs - Autres avoirs",	"Compte d''actif",	"Compte de bilan"),
            (4098,"Rabais, remises, ristournes à obtenir et autres avoirs non encore reçus",	"Compte d''actif",	"Compte de bilan"),
            (410,"Clients et comptes rattachés",	"Compte de l''actif ou de passif",	"Compte de bilan"),
            (411,"Clients",	"Compte de l''actif ou de passif",	"Compte de bilan"),
            (413,"Clients - Effets à recevoir",	"Compte d''actif",	"Compte de bilan"),
            ( 416,"Clients douteux ou litigieux",	"Compte d''actif",	"Compte de bilan"),
            (418,"Clients - Produits non encore facturés",	"Compte d''actif",	"Compte de bilan"),
            (419,"Clients créditeurs",	"Compte de passif",	"Compte de bilan"),
            (4191,"Clients - Avances et acomptes reçus sur commandes",	"Compte de passif",	"Compte de bilan"),
            (4196,"Clients - Dettes sur emballages et matériels consignés",	"Compte de passif","Compte de bilan"),
            (4197,"Clients - Autres avoirs",	"Compte de passif",	"Compte de bilan"),
            (4198,"Rabais, remises, ristournes à accorder et autres avoirs à établir",	"Compte de passif",	"Compte de bilan"),
            (421,"Personnel - Rémunérations dues",	"Compte de passif",	"Compte de bilan"),
            (422,"Comités d''entreprises, d''établissement, …",	"Compte de l''actif ou de passif",	"Compte de bilan"),
            (          424,"Participation des salariés aux résultats",	"Compte de passif",	"Compte de bilan"),
            (4246,"Participation des salariés aux résultats - Réserve spéciale",	"Compte de passif",	"Compte de bilan"),
            (4248,"Participation des salariés aux résultats - Comptes courants",	"Compte de passif",	"Compte de bilan"),
            (425,"Personnel - Avances et acomptes",	"Compte d''actif",	"Compte de bilan"),
            (     426,"Personnel - Dépôts",	"Compte de passif",	"Compte de bilan"),
            (427,"Personnel - Oppositions",	"Compte de passif",	"Compte de bilan"),
            (428,"Personnel - Charges à payer et produits à recevoir",	"Compte de passif",	"Compte de bilan"),
            (4282,"Personnel - Dettes provisionnées pour congés à payer",	"Compte de passif",	"Compte de bilan"),
            (4284,"Personnel - Dettes provisionnées pour participation des salariés aux résultats",	"Compte de passif",	"Compte de bilan"),
            (4286,"Personnel - Autres charges à payer",	"Compte de passif",	"Compte de bilan"),
            (4287,"Personnel - Produits à recevoir",	"Compte d''actif",	"Compte de bilan"),
            (       431,"Sécurité sociale",	"Compte d''actif",	"Compte de bilan"),
            (       437,"Autres organismes sociaux",	"Compte d''actif",	"Compte de bilan"),
            (      438,"Organismes sociaux - Charges à payer et produits à recevoir",	"Compte de l''actif ou de passif",	"Compte de bilan"),
            (      4382,"Organismes sociaux - Charges sociales sur congés à payer",	"Compte de passif",	"Compte de bilan"),
            (4386,"Organismes sociaux - Autres charges à payer",	"Compte de passif",	"Compte de bilan"),
            (4387,"Organismes sociaux - Produits à recevoir",	"Compte d''actif",	"Compte de bilan"),
            (440,"État et autres collectivités publiques",	"Compte de l''actif ou de passif",	"Compte de bilan"),
            ( 441,"État - Subventions à recevoir",	"Compte d''actif",	"Compte de bilan"),
            ( 442,"Etat - Impôts et taxes recouvrables sur des tiers",	"Compte de passif",	"Compte de bilan"),
            (443,"Opérations particulières avec l''Etat les collectivités publiques, les organismes internationaux",	"Compte de l''actif ou de passif",	"Compte de bilan"),
            (4431,"Créances sur l''Etat résultant de la suppression de la règle du décalage d''un mois en matière de",	"Compte d''actif",	"Compte de bilan"),
            (4438,"Intérêts courus sur créances figurant au 4431",	"Compte d''actif",	"Compte de bilan"),
            (444,"Etat - Impôts sur les bénéfices",	"Compte de l''actif ou de passif",	"Compte de bilan"),
            (445,"Etat - Taxes sur le chiffre d''affaires",	"Compte de l''actif ou de passif",	"Compte de bilan"),
            (4452,"TVA due intracommunautaire",	"Compte d''actif",	"Compte de bilan"),
            (4455,"Taxes sur le chiffre d''affaires à décaisser",	"Compte de passif",	"Compte de bilan"),
            (  44551,"TVA à décaisser",	"Compte de passif",	"Compte de bilan"),
            (44558,"Taxes assimilées à la TVA",	"Compte de passif",	"Compte de bilan"),
            (4456,"Taxes sur le chiffre d''affaires déductibles",	"Compte d''actif",	"Compte de bilan"),
            (44562,"TVA sur immobilisations",	"Compte d''actif",	"Compte de bilan"),
            (44563,"TVA transférée par d''autres entreprises",	"Compte d''actif",	"Compte de bilan"),
            (44566,"TVA sur autres biens et services",	"Compte d''actif"	,"Compte de bilan"),
            (44567,"Crédit de TVA à reporter",	"Compte d''actif",	"Compte de bilan"),
            ( 44568,"Taxes assimilées à la TVA",	"Compte d''actif",	"Compte de bilan"),
            ( 4457,"Taxes sur le chiffre d''affaires collectées par l''entreprise",	"Compte de passif",	"Compte de bilan"),
            (44571,"TVA collectée",	"Compte de passif",	"Compte de bilan"),
            (44578,"Taxes assimilées à la TVA",	"Compte de passif",	"Compte de bilan"),
            (4458,"Taxes sur le chiffre d''affaires à régulariser ou en attente",	"Compte de passif",	"Compte de bilan"),
            (44581,"Acomptes - Régime simplifié d''imposition",	"Compte d''actif",	"Compte de bilan"),
            (44582,"Acomptes - Régime de forfait",	"Compte d''actif",	"Compte de bilan"),
            (44583,"Remboursement de taxes sur le chiffre d''affaires demandé",	"Compte d''actif",	"Compte de bilan"),
            (44584,"TVA récupérée d''avance",	"Compte de passif",	"Compte de bilan"),
            (44586,"Taxes sur le chiffre d''affaires sur factures non parvenues",	"Compte d''actif",	"Compte de bilan"),
            (44587,"Taxes sur le chiffre d''affaires sur factures à établir",	"Compte de passif",	"Compte de bilan"),
            (446,"Obligations cautionnées",	"Compte de passif",	"Compte de bilan"),
            (447,"Autres impôts, taxes et versements assimilés",	"Compte de passif",	"Compte de bilan"),
            (448,"Etat - Charges à payer et produits à recevoir",	"Compte d''actif",	"Compte de bilan"),
            (4482,"Charges fiscales sur congés à payer",	"Compte de passif",	"Compte de bilan"),
            (4486,"Etat - Charges à payer",	"Compte de passif",	"Compte de bilan"),
            (4487,"Etat - produits à recevoir",	"Compte d''actif",	"Compte de bilan"),
            (   449,"Quotas d’émission à acquérir",	"Compte de passif",	"Compte de bilan"),
            (451,"Groupe",	"Compte de l''actif ou de passif",	"Compte de bilan"),
            ( 455,"Associés - Comptes courants",	"Compte de l''actif ou de passif",	"Compte de bilan"),
            ( 456,"Associés - Opérations sur le capital",	"Compte de l''actif ou de passif",	"Compte de bilan"),
            (  4561,"Associés - Comptes d''apport en société",	"Compte de l''actif ou de passif",	"Compte de bilan"),
            (45611,"Associés - Comptes d''apport en nature",	"Compte de l''actif ou de passif",	"Compte de bilan"),
            (45615,"Associés - Comptes d''apport en numéraire",	"Compte de l''actif ou de passif",	"Compte de bilan"),
            (4562,"Apporteurs - Capital appelé, non versé",	"Compte d''actif",	"Compte de bilan"),
            (45621,"Actionnaires - Capital souscrit et appelé, non versé",	"Compte d''actif",	"Compte de bilan"),
            ( 45625,"Associés - Capital appelé, non versé",	"Compte d''actif",	"Compte de bilan"),
            (  4563,"Associés - Versements reçus sur augmentation de capital",	"Compte de l''actif ou de passif",	"Compte de bilan"),
            ( 4564,"Associés - Versements anticipés",	"Compte de l''actif ou de passif",	"Compte de bilan"),
            ( 4566,"Actionnaires défaillants",	"Compte de l''actif ou de passif",	"Compte de bilan"),
            (  4567,"Associés - Capital à rembourser",	"Compte de l''actif ou de passif",	"Compte de bilan"),
            ( 457,"Associés - Dividendes à payer",	"Compte de passif",	"Compte de bilan"),
            (458,"Associés - Opérations faites en commun et en GIE",	"Compte de l''actif ou de passif",	"Compte de bilan"),
            (    460,"Débiteurs divers et créditeurs divers",	"Compte d''actif",	"Compte de bilan"),
            (     462,"Créances sur cessions d''immobilisations",	"Compte d''actif",	"Compte de bilan"),
            (464,"Dettes sur acquisitions de valeurs mobilières de placement",	"Compte de passif",	"Compte de bilan"),
            (465,"Créances sur cessions de valeurs mobilières de placement",	"Compte d''actif",	"Compte de bilan"),
            (   467,"Autres comptes débiteurs ou créditeurs",	"Compte de l''actif ou de passif",	"Compte de bilan"),
            (   468,"Divers - Charges à payer et produits à recevoir",	"Compte de l''actif ou de passif",	"Compte de bilan"),
            (  4686,"Charges à payer",	"Compte de passif",	"Compte de bilan"),
            (4687,"Produits à recevoir",	"Compte d''actif",	"Compte de bilan"),
            (    470,"Comptes transitoires ou d''attente",	"Compte de l''actif ou de passif",	"Compte de bilan"),
            (471,"Comptes d''attente",	"Compte de l''actif ou de passif",	"Compte de bilan"),
            (476,"Différence de conversion - Actif",	"Compte d''actif",	"Compte de bilan"),
            (   477,"Différences de conversion - Passif",	"Compte de passif",	"Compte de bilan"),
            (478,"Autres comptes transitoires",	"Compte de l''actif ou de passif",	"Compte de bilan"),
            (   480,"Comptes de régularisation",	"Compte de l''actif ou de passif",	"Compte de bilan"),
            (   481,"Charges à répartir sur plusieurs exercices",	"Compte d''actif",	"Compte de bilan"),
            (   4816,"Frais d''émission des emprunts",	"Compte d''actif",	"Compte de bilan"),
            (486,"Charges constatées d''avance",	"Compte d''actif",	"Compte de bilan"),
            (487,"Produits constatés d''avance",	"Compte de passif",	"Compte de bilan"),
            (   488,"Comptes de répartition périodique des charges et des produits",	"Compte de l''actif ou de passif",	"Compte de bilan"),
            (  4886,"Comptes de répartition périodique des charges",	"Compte d''actif",	"Compte de bilan"),
            ( 4887,"Comptes de répartition périodique des produits",	"Compte de passif",	"Compte de bilan"),
            (491,"Dépréciations des comptes de clients",	"Compte d''actif",	"Compte de bilan"),
            ( 495,"Dépréciations des comptes du groupe et des associés",	"Compte d''actif",	"Compte de bilan"),
            (496,"Dépréciations des comptes de débiteurs divers",	"Compte d''actif",	"Compte de bilan"),
            (409,"Fournisseurs débiteurs",	"Compte d''actif",	"Compte de bilan"),
             -- Classe 5 : Les comptes financiers
            (50	,"Valeurs mobilières de placement",	"Compte d''actif",	"Compte de bilan"),
            ( 501,"VMP - Parts dans des entreprises liées",	"Compte d''actif",	"Compte de bilan"),
            (  502,"Actions propres",	"Compte d''actif",	"Compte de bilan"),
            (  5021,"Actons destinées à être attribuées aux employés et affectées à des plans déterminés",	"Compte d''actif",	"Compte de bilan"),
            (  5022,"Actons disponibles pour être attribuées aux employés ou pour la régularisation des cours de bourse",	"Compte d''actif",	"Compte de bilan"),
            (  503,"Actions",	"Compte d''actif",	"Compte de bilan"),
            ( 504,"Autres titres conférant un droit de propriété",	"Compte d''actif",	"Compte de bilan"),
            ( 505,"Obligations et bons émis par la société et rachetés par elle",	"Compte d''actif",	"Compte de bilan"),
            (506,"Obligations",	"Compte d''actif",	"Compte de bilan"),
            (507,"Bons du Trésor et bons de caisse à court terme",	"Compte d''actif",	"Compte de bilan"),
            (508,"Autres valeurs mobilières de placement et autres créances assimilées",	"Compte d''actif",	"Compte de bilan"),
            (5081,"Autres valeurs mobilières",	"Compte d''actif",	"Compte de bilan"),
            ( 5082,"Bons de souscription",	"Compte d''actif",	"Compte de bilan"),
            (5088,"Intérêts courus sur obligations, bons et valeurs assimilés",	"Compte d''actif",	"Compte de bilan"),
            (509,"Versements restant à effectuer sur valeurs mobilières de placement non libérées",	"Compte d''actif",	"Compte de bilan"),
            (510,"Banques, établissements financiers et assimilés",	"Compte de l''actif ou de passif",	"Compte de bilan"),
            (511,"Valeurs à l''encaissement",	"Compte de l''actif ou de passif",	"Compte de bilan"),
            (5111,"Coupons échus à l''encaissement",	"Compte de l''actif ou de passif",	"Compte de bilan"),
            (5112,"Chèques à encaisser",	"Compte de l''actif ou de passif",	"Compte de bilan"),
            (5113,"Effets à l''encaissement",	"Compte de l''actif ou de passif",	"Compte de bilan"),
            (5114,"Effets à l''escompte",	"Compte de l''actif ou de passif",	"Compte de bilan"),
            (512,"Banques",	"Compte de l''actif ou de passif",	"Compte de bilan"),
            (514,"Chèques postaux",	"Compte de l''actif ou de passif",	"Compte de bilan"),
            ( 515,"\" Caisses \" du Trésor et des établissements publics",	"Compte de l''actif ou de passif",	"Compte de bilan"),
            ( 516,"Sociétés de bourse",	"Compte de l''actif ou de passif",	"Compte de bilan"),
            ( 517,"Autres organismes financiers",	"Compte de l''actif ou de passif",	"Compte de bilan"),
            ( 518,"Intérêts courus",	"Compte d''actif",	"Compte de bilan"),
            ( 5181,"Intérêts courus à payer",	"Compte d''actif",	"Compte de bilan"),
            ( 5188,"Intérêts courus à recevoir",	"Compte d''actif",	"Compte de bilan"),
            ( 519,"Concours bancaires courants",	"Compte de l''actif ou de passif",	"Compte de bilan"),
            (  520,"Instruments de trésorerie",	"Compte de l''actif ou de passif",	"Compte de bilan"),
            (  530,"Caisse",	"Compte d''actif",	"Compte de bilan"),
            (  531,"Caisse siège social",	"Compte d''actif",	"Compte de bilan"),
            ( 532,"Caisse succursale (ou usine) A",	"Compte d''actif",	"Compte de bilan"),
            ( 533,"Caisse succursale (ou usine) B",	"Compte d''actif",	"Compte de bilan"),
            ( 540,"Régies d''avance et accréditifs",	"Compte d''actif",	"Compte de bilan"),
            (580,"Virements internes",	"Compte de l''actif ou de passif",	"Compte de bilan"),
            ( 590,"Dépréciations des valeurs mobilières de placement",	"Compte d''actif",	"Compte de bilan"),
            (5903,"Dépréciations des VMP - Actions",	"Compte d''actif",	"Compte de bilan"),
            ( 5904,"Dépréciations des VMP - Autres titres conférant un droit de propriété",	"Compte d''actif",	"Compte de bilan"),
            ( 5906,"Dépréciations des VMP - Obligations",	"Compte d''actif",	"Compte de bilan"),
            ( 5908,"Dépréciations des VMP - Autres valeurs mobilières de placement et créances assimilées",	"Compte d''actif",	"Compte de bilan"),


   -- Classe 6 : Les comptes de charges
            (601,"Achats stockés - Matières premières (et fournitures)",	"",	"Compte de gestion"),
            (602,"Achats stockés - Autres approvisionnements",	"",	"Compte de gestion"),
            (6021,"Achats stockés - Matières consommables", "",	"Compte de gestion"),
            (6022,"Achats stockés - Fournitures consommables",	"",	"Compte de gestion"),
            (6026,"Achats stockés - Emballages",	"",	"Compte de gestion"),
            (604,"Achats d''études et prestations de services",	"Compte d''actif",	"Compte de gestion"),
            (605,"Achats de matériel, équipements et travaux",	"",	"Compte de gestion"),
            (606,"Achats non stockés de matière et fournitures", "",		"Compte de gestion"),
            (6061,"Achats non de fournitures non stockables (eau, énergie, …)", "",	"Compte de gestion"),
            (6063,"Achats de fournitures d''entretien et de petit équipement", "",		"Compte de gestion"),
            ( 6064,"Achats de fournitures administratives", "",		"Compte de gestion"),
            (6068,"Achats d''autres matières et fournitures", "",		"Compte de gestion"),
            (607,"Achats de marchandises", "",	"Compte de gestion"),
            (608,"(Compte réservé, le cas échéant, à la récapitulation des frais accessoires incorporés aux achats)", "Compte d''actif",	"Compte de gestion"),
            (609,"Rabais, remises et ristournes obtenus sur achats", "",		"Compte de gestion"),
            (603,"Variations des stocks (approvisionnements et marchandises)", "",		"Compte de gestion"),
            (6031,"Variation des stocks de matières premières (et fournitures)", "",		"Compte de gestion"),
            (6032,"Variation des stocks des autres approvisionnements", "",		"Compte de gestion"),
            (6037,"Variation des stocks de marchandises", "",		"Compte de gestion"),
            (610,"Services extérieurs", "",		"Compte de gestion"),
            (611,"Sous-traitance générale", "",	"Compte de gestion"),
            (612,"Redevances de crédit-bail","",	"Compte de gestion"),
            (6122,"Redevances de rédit-bail mobilier", "",		"Compte de gestion"),
            (6125,"Redevances de crédit-bail immobilier", "",		"Compte de gestion"),
            (613	,"Locations", "",		"Compte de gestion"),
            (6132,"Locations immobilières", "",	"Compte de gestion"),
            (6135,"Locations mobilières", "",		"Compte de gestion"),
            (6136,"Malis sur emballages", "",		"Compte de gestion"),
            (614,"Charges locatives et de copropriété", "",		"Compte de gestion"),
            (615	,"Entretien et réparations", "",		"Compte de gestion"),
            (6152,"Entretien et réparations sur biens immobiliers", "",	"Compte de gestion"),
            (6155,"Entretien et réparations sur biens mobiliers", "",	"Compte de gestion"),
            (6156,"Maintenance", "",	"Compte de gestion"),
            (616,"Primes d''assurances",	"",	"Compte de gestion"),
            ( 617,"Etudes et recherches", "",	"Compte de gestion"),
            (618,"Divers", "",	"Compte de gestion"),
            (6181,"Divers - Documentation générale", "",	"Compte de gestion"),
            (6183,"Divers - Documentation technique", "",	"Compte de gestion"),
            (6185,"Divers - Frais de collogues, séminaires, conférences",	"",	"Compte de gestion"),
            (619,"Rabais, remises et ristournes obtenus sur services extérieurs", "",	"Compte de gestion"),
            (620,"Autres services extérieurs", "",	"Compte de gestion"),
            (621,"Personnel extérieur à l''entreprise", "",	"Compte de gestion"),
            ( 6211,"Personnel intérimaire",	"",	"Compte de gestion"),
            (6214,"Personnel détaché ou prêté à l''entreprise",	"",	"Compte de gestion"),
            (622,"Rémunérations d''intermédiaires et honoraires", "",	"Compte de gestion"),
            (  6221,"Commissions et courtages sur achats",	"",	"Compte de gestion"),
            (6222,"Commissions et courtages sur ventes", "",		"Compte de gestion"),
            (6224,"Rémunérations des transitaires",	"",	"Compte de gestion"),
            (6225,"Rémunérations d''affacturage", "", "Compte de gestion"),
            ( 6226,"Honoraires",	"",	"Compte de gestion"),
            (6227,"Frais d''actes et de contentieux",	"",	"Compte de gestion"),
            (  6228,"Rémunérations d''intermédiaires et honoraires - Divers", "",	"Compte de gestion"),
            (    623,"Publicité, publications, relations publiques", "",	"Compte de gestion"),
            (624,"Transports de biens et transports collectifs du personnel", "", "Compte de gestion"),
            (6241,"Transports sur achats", "",	"Compte de gestion"),
            (6242,"Transports sur ventes",	"",	"Compte de gestion"),
            (625,"Déplacements, missions et réceptions",	"", "Compte de gestion"),
            (6251,"Voyages et déplacements", "",	"Compte de gestion"),
            (6257,"Réceptions",	"",	"Compte de gestion"),
            (626,"Frais postaux et de télécommunications",	"",	"Compte de gestion"),
            (627,"Services bancaires et assimilés", "",	"Compte de gestion"),
            (628,"Autres services extérieurs - Divers",	"",	"Compte de gestion"),
            (629,"Rabais, remises et ristournes obtenus sur autres services extérieurs",	"",	"Compte de gestion"),
            (630,"Impôts, taxes et versements assimilés", "",	"Compte de gestion"),
            (631,"Impôts, taxes et versements assimilés sur rémunérations (administrations des impôts)", "",	"Compte de gestion"),
            (6311,"Taxe sur les salaires", "",		"Compte de gestion"),
            (6312,"Taxe d''apprentissage", "",	"Compte de gestion"),
            ( 6313,"Participation des employeurs à la formation professionnelle continue", "",	"Compte de gestion"),
            (6314,"Cotisation pour défaut d''investissement obligatoire dans la construction", "",	"Compte de gestion"),
            (  6318,"Impôts, taxes et versements assimilés sur rémunérations (administrations des impôts) - Autres" ,"", "Compte de gestion"),
            (633,"Impôts, taxes et versements assimilés sur rémunérations (autres organismes)", "",	"Compte de gestion"),
            (6331,"Versement de transport", "",	"Compte de gestion"),
            (6332,"Allocations logement", "",	"Compte de gestion"),
            (6333,"Participation des employeurs à la formation professionnelle continue", "", "Compte de gestion"),
            (6334,"Participation des employeurs à l''effort de construction", "",		"Compte de gestion"),
            (           6335,"Versements libératoires ouvrant droit à l''exonération de la taxe d''apprentissage", "", "Compte de gestion"),
            (6338,"Impôts, taxes et versements assimilés sur rémunérations (autres organismes) - Autres" , "",		"Compte de gestion"),
            (635,"Autres impôts, taxes et versements assimilés (administrations des impôts)", "", 	"Compte de gestion"),
            (6351,"Impôts directs (sauf impôts sur les bénéfices)", "", "Compte de gestion"),
            (63511,"Contribution économique territoriale", "", "Compte de gestion"),
            (63512,"Taxes foncières", "",	"Compte de gestion"),
            (63513,"Autres impôts locaux", "",	"Compte de gestion"),
            (63514,"Taxe sur les véhicules des sociétés", "",	"Compte de gestion"),
            (6352,"Taxe sur le chiffre d''affaires non récupérables", "",	"Compte de gestion"),
            (           6353,"Impôts indirects", "",	"Compte de gestion"),
            (6354,"Droits d''enregistrement et de timbre", "", "Compte de gestion"),
            (           6358,"Autres droits", "",		"Compte de gestion"),
            (637,"Autres impôts, taxes et versements assimilés (autres organismes)", "", "Compte de gestion"),
            (640,"Charges de personnel", "",	"Compte de gestion"),
            (641,"Rémunérations du personnel", "", "Compte de gestion"),
            (6411,"Rémunérations du personnel - Salaires, appointements", "",	"Compte de gestion"),
            (6412,"Rémunérations du personnel - Congés payés", "",	"Compte de gestion"),
            (6413,"Rémunérations du personnel - Primes et gratifications", "",	"Compte de gestion"),
            (6414,"Rémunérations du personnel - Indemnités et avantages divers", "",	"Compte de gestion"),
            (6415,"Rémunérations du personnel - Supplément familial", "", "Compte de gestion"),
            (644,"Rémunération du travail de l''exploitant", "",	"Compte de gestion"),
            (            645,"Charges de sécurité sociale et de prévoyance", "", "Compte de gestion"),
            (6451,"Cotisations à l''URSSAF", "",		"Compte de gestion"),
            (            6452,"Cotisations aux mutuelles", "",	"Compte de gestion"),
            (6453,"Cotisations aux caisses de retraites" , "",		"Compte de gestion"),
            (6454,"Cotisations aux ASSEDIC",	"", "Compte de gestion"),
            (6458,"Cotisations aux autres organismes sociaux", "",	"Compte de gestion"),
            (646	,"Cotisations sociales personnelles de l''exploitant", "", "Compte de gestion"),
            (           647,"Autres charges sociales", "", "Compte de gestion"),
            (6475,"Médecine du travail, pharmacie", "Compte d''actif",	"Compte de gestion"),
            (      648,"Autres charges de personnel", "",		"Compte de gestion"),
            (650,"Autres charges de gestion courante", "",	"Compte de gestion"),
            (651,"Redevances pour concessions, brevets, licences, marques, procédés, logiciels, droits et valeurs", "",	"Compte de gestion"),
            (653,"Jetons de présence", "", "Compte de gestion"),
            (654,"Pertes sur créances irrécouvrables",	"",	"Compte de gestion"),
            (655,"Quote-part de résultat sur opérations faites en commun", "",	"Compte de gestion"),
            (658,"Charges diverses de gestion courante", "",	"Compte de gestion"),
            (660,"Charges financières", "",	"Compte de gestion"),
            (661,"Charges d''intérêts", "", "Compte de gestion"),
            (            6611,"Intérêts des emprunts et dettes", "", "Compte de gestion"),
            (6616,"Intérêts bancaires et sur opérations de financement", "", "Compte de gestion"),
            (664,"Pertes sur créances liées à des participations", "", "Compte de gestion"),
            (665,"Escomptes accordés", "",	"Compte de gestion"),
            (666,"Pertes de change", "", "Compte de gestion"),
            (667,"Charges nettes sur cessions de valeurs mobilières de placement", "", "Compte de gestion"),
            (668,"Autres charges financières", "", "Compte de gestion"),
            (670,"Charges exceptionnelles", "", "Compte de gestion"),
            (671,"Charges exceptionnelles sur opérations de gestion", "", "Compte de gestion"),
            (672,"(Compte à la disposition des entités pour enregistrer, en cours d''exercice, les charges sur exercices", "", "Compte de gestion"),
            (            674,"Opérations de constitution ou liquidation des fiducies", "", "Compte de gestion"),
            (675,"Valeurs comptables des éléments d''actif cédés", "",	"Compte de gestion"),
            (            678,"Autres charges exceptionnelles", "", "Compte de gestion"),
            (680,"Dotations aux amortissements, aux dépréciations et aux provisions", "", "Compte de gestion"),
            (681,"Dotations aux amortissements, aux dépréciations et aux provisions - Charges d''exploitation", "", "Compte de gestion"),
            (            6811,"Dotations aux amortissements sur immobilisations incorporelles et corporelles", "",	"Compte de gestion"),
            (6812,"Dotations aux amortissements des charges d''exploitation à répartir", "",		"Compte de gestion"),
            (         6815,"Dotations aux provisions d''exploitation", "", "Compte de gestion"),
            (         6816,"Dotations pour dépréciations des immobilisations incorporelles et corporelles", "", "Compte de gestion"),
            (6817,"Dotations pour dépréciations des actifs circulants", "",	"Compte de gestion"),
            (68173,"Dotations pour dépréciations des actifs circulants - Stocks et en-cours", "", "Compte de gestion"),
            (68174,"Dotations pour dépréciations des actifs circulants - Créances", "",	"Compte de gestion"),
            (686,"Dotations aux amortissements, aux dépréciations et aux provisions - Charges financières", "", "Compte de gestion"),
            (687,"Dotations aux amortissements, aux dépréciations et aux provisions - Charges exceptionnelles", "", "Compte de gestion"),
            (690,"Participation des salariés - Impôts sur les bénéfices et assimilés", "",	"Compte de gestion"),
            (691,"Participation des salariés aux résultats", "",		"Compte de gestion"),
            (695,"Impôts sur les bénéfices", "", "Compte de gestion"),
            (696,"Suppléments d''impôt sur les sociétés liés aux distributions", "",	"Compte de gestion"),
            ( 698,"Intégration fiscale", "",	"Compte de gestion"),
            (699,"Produits - Reports en arrière des déficits", "", "Compte de gestion"),
            (6417,"Rémunérations du personnel - Avantages en nature", "",	"Compte de gestion"),
            (6712,"Pénalités, amendes fiscales et pénales", "Compte d''actif", "Compte de gestion"),
            (   6715,"Subventions accordées", "", "Compte de gestion"),
            (6756,"Valeurs comptables des éléments d''actifs cédés - Immobilisations financières", "", "Compte de gestion"),
            ( 6781,"Malis provenant de clauses d''indexation", "", 	"Compte de gestion"),
            ( 6875,"Dotations aux provisions exceptionnelles",	"",	"Compte de gestion"),
            (68725,"Dotations aux amortissements dérogatoires", "", "Compte de gestion"),
            (6865,"Dotations aux provisions financières", "", "Compte de gestion"),
   -- Classe 7 : Les comptes de produits
            (700,"Ventes de produits fabriqués, prestations de services, marchandises","","Compte de gestion"),
            (701,"Ventes de produits finis","","Compte de gestion"),
            (702,"Ventes de produits intermédiaires","","Compte de gestion"),
            (703,"Ventes de produits résiduels","","Compte de gestion"),
            (704,"Travaux","","Compte de gestion"),
            (705,"Etudes","","Compte de gestion"),
            (706,"Prestations de services","","Compte de gestion"),
            (707,"Ventes de marchandises","","Compte de gestion"),
            (708,"Produits des activités annexes	Compte d''actif","","Compte de gestion"),
            (           7085,"Produits des activités annexes - Ports et frais accessoires facturés","","Compte de gestion"),
            (709,"Rabais, remises et ristournes accordés par l''entreprise","","Compte de gestion"),
            (            710,"Production stockée (ou déstockage)","","Compte de gestion"),
            (713,"Variation des stocks (en-cours de production, produits)","","Compte de gestion"),
            (7133,"Variation des en-cours de production de biens","","Compte de gestion"),
            (7134,"Variation des en-cours de production de services","","Compte de gestion"),
            (7135,"Variation des stocks de produits","","Compte de gestion"),
            (720,"Production immobilisée","","Compte de gestion"),
            (721,"Production immobilisée - Immobilisations incorporelles","","Compte de gestion"),
            (722,"Production immobilisée - Immobilisations corporelles",	"Compte d''actif","Compte de gestion"),
            (            740,"Subventions d''exploitation","","Compte de gestion"),
            (            750,"Autres produits de gestion courante","","Compte de gestion"),
            (751,"Redevances pour concessions, brevets, licences, marques, procédés, logiciels, droits et valeurs","","Compte de gestion"),
            (752,"Revenus des immeubles non affectés à des activités professionnelles","","Compte de gestion"),
            (753,"Jetons de présence et rémunérations d''administrateurs, gérants","","Compte de gestion"),
            (754,"Ristournes perçues des coopératives (provenant des excédents)","","Compte de gestion"),
            (755,"Quote-parts de résultat sur opérations faites en commun","","Compte de gestion"),
            (758,"Produits divers de gestion courante","","Compte de gestion"),
            (760,"Produits financiers","","Compte de gestion"),
            (761,"Produits de participations","","Compte de gestion"),
            (762,"Produits des autres immobilisations financières","","Compte de gestion"),
            (763,"Revenus des autres créances","","Compte de gestion"),
            (764,"Revenus des valeurs mobilières de placement","","Compte de gestion"),
            (765,"Escomptes obtenus","","Compte de gestion"),
            (766,"Gains de change","","Compte de gestion"),
            (767,"Produits nets sur cessions de valeurs mobilières de placement","","Compte de gestion"),
            (768,"Autres produits financiers","","Compte de gestion"),
            (770,"Produits exceptionnels","","Compte de gestion"),
            (771,"Produits exceptionnels sur opérations de gestion","","Compte de gestion"),
            (772,"(Compte à la disposition des entités pour enregistrer, en cours d''exercice, les produits sur exercices antérieurs)","","Compte de gestion"),
            ( 774,"Opérations de constitution ou liquidation des fiducies","","Compte de gestion"),
            (775,"Produits des cessions d''éléments d''actif","","Compte de gestion"),
            (777,"Quote-part des subventions d''investissement virée au résultat de l''exercice","","Compte de gestion"),
            (778,"Autres produits exceptionnels","","Compte de gestion"),
            (7781,"Bonis provenant de clauses d''indexation","","Compte de gestion"),
            (7783,"Bonis provenant du rachat par l''entreprise d''actions et d''obligations émises par elle - même","","Compte de gestion"),
            (780,"Reprises sur amortissements, dépréciations et provisions","","Compte de gestion"),
            (781,"Reprises sur amortissements, dépréciations et provisions (à inscrire dans les produits d''exploitation)","","Compte de gestion"),
            (7811,"Reprises sur amortissements des immobilisations incorporelles et corporelles","","Compte de gestion"),
            (78111,"Reprises sur amortissements des immobilisations incorporelles","","Compte de gestion"),
            (78112,"Reprises sur amortissements des immobilisations corporelles","","Compte de gestion"),
            (7815,"Reprises sur provisions d''exploitation","","Compte de gestion"),
            (7816,"Reprises sur dépréciations des immobilisations incorporelles et corporelles","","Compte de gestion"),
            (78161,"Reprises sur dépréciations des immobilisations incorporelles","","Compte de gestion"),
            (78162,"Reprises sur dépréciations des immobilisations corporelles","","Compte de gestion"),
            (7817,"Reprises sur dépréciations des actifs circulants","","Compte de gestion"),
            (786,"Reprises sur provisions pour risques et dépréciations (à inscrire dans les produits financiers)","","Compte de gestion"),
            (7865,"Reprises sur provisions financières","","Compte de gestion"),
            (7866,"Reprises sur dépréciations des éléments financiers","","Compte de gestion"),
            (787,"Reprises sur provisions et dépréciations (à inscrire dans les produits exceptionnels)","","Compte de gestion"),
            (78725,"Reprises sur provisions réglementées (immobilisations) - Amortissements dérogatoires","","Compte de gestion"),
            (7873,"Reprises sur provisions réglementées (stocks)", "","Compte de gestion"),
            (7874,"Reprises sur autres provisions réglementées","","Compte de gestion"),
            (7876,"Reprises sur dépréciations exceptionnelles","","Compte de gestion"),
            (791,"Transferts de charges d''exploitation","","Compte de gestion"),
            (796,"Transferts de charges financières","",	"Compte de gestion"),
            (797,"Transferts de charges exceptionnelles","","Compte de gestion"),
            (7875,"Reprises sur provisions exceptionnelles","","Compte de gestion"),
            (7756,"Prix de cession des éléments d''actifs - Immobilisations financières","","Compte de gestion"),
            (7715,"	Subventions d''équilibre","","Compte de gestion");